// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class AccountModel
{
    public Guid AccountId { get; set; }

    public Guid? EmployeeId { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public DateTime? LastLogin { get; set; }

    public bool? Active { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? LastEditBy { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastEditTime { get; set; }

    public virtual EmployeeModel Employee { get; set; }

    public virtual ICollection<RoleModel> Roles { get; set; } = new List<RoleModel>();
}