// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class FunctionModel
{
    public Guid FunctionId { get; set; }

    public string FunctionCode { get; set; }

    public string FunctionName { get; set; }

    public virtual ICollection<RolePageFunctionMapping> RolePageFunctionMappings { get; set; } = new List<RolePageFunctionMapping>();

    public virtual ICollection<PageModel> Pages { get; set; } = new List<PageModel>();
}