// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class MenuModel
{
    public Guid MenuId { get; set; }

    public string MenuCode { get; set; }

    public string MenuName { get; set; }

    public string Icon { get; set; }

    public int? OrderIndex { get; set; }

    public bool? Active { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? LastEditBy { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastEditTime { get; set; }

    public virtual ICollection<PageModel> PageModels { get; set; } = new List<PageModel>();
}