// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class PageModel
{
    public Guid PageId { get; set; }

    public Guid? MenuId { get; set; }

    public string PageCode { get; set; }

    public string PageName { get; set; }

    public string PageUrl { get; set; }

    public string PageIcon { get; set; }

    public int? OrderIndex { get; set; }

    public bool? Active { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? LastEditBy { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? LastEditTime { get; set; }

    public virtual MenuModel Menu { get; set; }

    public virtual ICollection<RolePageFunctionMapping> RolePageFunctionMappings { get; set; } = new List<RolePageFunctionMapping>();

    public virtual ICollection<FunctionModel> Functions { get; set; } = new List<FunctionModel>();
}