// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class ProductModel
{
    public Guid ProductId { get; set; }

    public Guid? BrandId { get; set; }

    public Guid? SubBrandId { get; set; }

    public Guid? GroupId { get; set; }

    public Guid? SubGroupId { get; set; }

    public int CommerrcialCode { get; set; }

    public string ErpproductCode { get; set; }

    public string ProductName { get; set; }

    public string ShortName { get; set; }

    public string Unit { get; set; }

    public int? NumActivedSys { get; set; }

    public bool? Actived { get; set; }

    public bool? IsRequiredSerial { get; set; }

    public string Note { get; set; }

    public Guid? CreateBy { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? LastEditBy { get; set; }

    public DateTime? LastEditTime { get; set; }

    public string ProductCode { get; set; }

    public decimal? CylinderCapacity { get; set; }

    public Guid? CategoryId { get; set; }

    public Guid? ConfigurationId { get; set; }

    public string GuaranteePeriod { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsHot { get; set; }

    public int? OrderIndex { get; set; }

    public Guid? ParentCategoryId { get; set; }

    public Guid? CompanyId { get; set; }

    public bool? IsInventory { get; set; }

    public decimal? SampleValue { get; set; }

    public decimal? ProcessingValue { get; set; }

    public decimal? Price { get; set; }

    public Guid? WarrantyId { get; set; }

    public string ProductGroups { get; set; }

    public decimal? SafeStock { get; set; }

    public string WarrantyConditionCode { get; set; }

    public int? WarrantyDate { get; set; }

    public int? ExpriedMaintenance { get; set; }
}