// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class RolePageFunctionMapping
{
    public Guid RoleId { get; set; }

    public Guid PageId { get; set; }

    public Guid FunctionId { get; set; }

    public virtual FunctionModel Function { get; set; }

    public virtual PageModel Page { get; set; }

    public virtual RoleModel Role { get; set; }
}