// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.Entites;

public partial class StoreModel
{
    public Guid StoreId { get; set; }

    public string SaleOrgCode { get; set; }

    public Guid? StoreTypeId { get; set; }

    public string StoreName { get; set; }

    public Guid CompanyId { get; set; }

    public string TelProduct { get; set; }

    public string TelService { get; set; }

    public string StoreAddress { get; set; }

    public string Area { get; set; }

    public Guid? ProvinceId { get; set; }

    public Guid? DistrictId { get; set; }

    public string Email { get; set; }

    public string Fax { get; set; }

    public string LogoUrl { get; set; }

    public string ImageUrl { get; set; }

    public int? OrderIndex { get; set; }

    public bool Actived { get; set; }

    public string MLat { get; set; }

    public string MLong { get; set; }

    public string InvoiceStoreName { get; set; }

    public string DefaultCustomerSource { get; set; }

    public string SmstemplateCode { get; set; }

    public Guid? CreateBy { get; set; }

    public DateTime? CreateTime { get; set; }

    public Guid? LastEditBy { get; set; }

    public DateTime? LastEditTime { get; set; }
}